export const ActionTypes = {
    MOVİES_LOADING: "MOVİES_LOADING",
    MOVİES_SUCCESS: "MOVİES_SUCCESS",
    MOVİES_ERROR: "MOVİES_ERROR",
    GENRES_LOADING: "GENRES_LOADING",
    GENRES_SUCCESS: "GENRES_SUCCESS",
    GENRES_ERROR: "GENRES_ERROR",
};

